{{- if .Values.global.namespace.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.appconfig.appnamespace }}
  labels:
    name: {{ .Values.appconfig.appnamespace }}
{{- end }}