tosca_definitions_version: tosca_simple_profile_yaml_1_2
description: Eastcom SPCLNLWY EMS
imports:
  - nfv_vnfd_types_v1_0.yaml

metadata:
  template_name: Eastcom-SPCLNLWY-EMS_eulerforTR6_iso
  template_author: eastcom
  template_version: 1.0.0
  vnfm_type: MEPM
  vnfd_id: eulerforTR6_iso_arm
  vnfd_version: v3.25
  vnfd_name: eastcom_spclnlwyems_eulerforTR6_iso_vnfd
  vnfd_description: spclnlwyems vnfd for gvnfm

topology_template:
  inputs:
    network_name_mep:
      type: string
        default: mec_newwork_mep
        description: network_name_mep
    network_name_n6:
      type: string
        default: mec_newwork_n6
        description: network_name_n6
    network_name_internet:
      type: string
        default: mec_newwork_internet
        description: network_name_internet
    network_internet_physnet:
      type: string
        default: network_internet_physnet
        description: network_internet_physnet
    network_internet_vlanid:
      type: string
        default: network_internet_vlanid
        description: network_internet_vlanid
    network_n6_physnet:
      type: string
        default: network_n6_physnet
        description: network_n6_physnet
    network_n6_vlanid:
      type: string
        default: network_n6_vlanid
        description: network_n6_vlanid
    network_mep_physnet:
      type: string
        default: network_mep_physnet
        description: network_mep_physnet
    network_mep_vlanid:
      type: string
        default: network_mep_vlanid
        description: network_mep_vlanid

    INTERNAL_IP_VERSION:
      type: string
      default: IPV4
      description: INTERNAL_IP_VERSION
    DEMO_VNF_Network_01:
      type: string
      default: app_arm
      description: DEMO_VNF_Network_01
    DEMO_VNF_Network_02:
      type: string
      default: app_arm
      description: DEMO_VNF_Network_02


  node_templates:
    Simple_VNF:
      type: tosca.nodes.nfv.VNF
      properties:
        vnfd_id: eulerforTR6_iso_arm_zhi_new1
        vnfd_version: v1.0
        provider: eastcom
        product_name: vSPCLNLWYEMS
        software_version: v1.0.0
        product_info_name: vSPCLNLWYEMS
        product_info_description: EASTCOM vSPCLNLWY EMS
        flavour_id: default
        flavour_description: default flavor
        ve_vnfm_vnf_enable: false
        ve_vnfm_em_enable: false

    EMS_VDU1:
      type: tosca.nodes.nfv.Vdu.Compute
      capabilities:
        virtual_compute:
          properties:
            virtual_memory:
              virtual_mem_size: 4096
            virtual_cpu:
              num_virtual_cpu: 4
              cpu_architecture: ARM
            virtual_local_storage:
              size_of_storage: 100
      properties:
        name: eulerforTR6_iso_arm_EMS_VDU1
        description: EMS_VDU1 node
        nfvi_constraints: 'nova'
        vdu_profile:
          min_number_of_instances: 1
          max_number_of_instances: 1
          initial_number_of_instances: 1
          flavor_extra_specs:
            "mgmt_egx86": "true"
        sw_image_data:
          name: ubuntu
        bootdata:
          config_drive: true
          user_data:
            contents:

    EMS_VDU1_CP0:
      type: tosca.nodes.nfv.VduCp
      properties:
        description: to mep
        vnic_name: eth0
        order: 0
        vnic_type: normal
        port_security_enabled: true
      requirements:
        - virtual_binding: EMS_VDU1
        - virtual_link: MEC_APP_MP1

    EMS_VDU1_CP1:
      type: tosca.nodes.nfv.VduCp
      properties:
        description: internal
        vnic_name: eth1
        order: 1
        vnic_type: normal
        port_security_enabled: true
      requirements:
        - virtual_binding: EMS_VDU1
        - virtual_link: MEC_APP_INTERNET

    EMS_VDU1_CP2:
      type: tosca.nodes.nfv.VduCp
      properties:
        description: to UFP&OM
        vnic_name: eth2
        order: 2
        vnic_type: normal
        port_security_enabled: true
      requirements:
        - virtual_binding: EMS_VDU1
        - virtual_link: MEC_APP_N6

    MEC_APP_MP1:
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: network_name_mep}
          network_type: vlan
          physical_network: {get_input: network_mep_physnet}
          provider_segmentation_id: {get_input: network_mep_vlanid}

    MEC_APP_INTERNET:
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: network_name_internet}
          network_type: vlan
          physical_network: {get_input: network_internet_physnet}
          provider_segmentation_id: {get_input: network_internet_vlanid}

    MEC_APP_N6:
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: network_name_n6}
          network_type: vlan
          physical_network: {get_input: network_n6_physnet}
          provider_segmentation_id: {get_input: network_n6_vlanid}


    DEMO_VL1: # 使用虚拟层中已经创建的网络名称或UUID。
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: DEMO_VNF_Network_01}

    DEMO_VL2: # 使用虚拟层中已经创建的网络名称或UUID。
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: DEMO_VNF_Network_02}

  groups:
    AntiAffinityGroup:
      type: tosca.groups.nfv.PlacementGroup
      properties:
        description: antiaffinity group
      members: [EMS_VDU1]
  policies:
    - antiaffinity_policy:
        type: tosca.policies.nfv.AntiAffinityRule
        targets: [AntiAffinityGroup]
        properties:
          scope: nfvi_node
          enforced: true
