tosca_definitions_version: tosca_simple_profile_yaml_1_2
description: Eastcom SPCLNLWY EMS
imports:
  - nfv_vnfd_types_v1_0.yaml

metadata:
  template_name: Eastcom-SPCLNLWY-EMS_eulerforTR6_iso
  template_author: eastcom
  template_version: 1.0.0
  vnfm_type: MEPM
  vnfd_id: eulerforTR6_iso_arm
  vnfd_version: v3.25
  vnfd_name: eastcom_spclnlwyems_eulerforTR6_iso_vnfd
  vnfd_description: spclnlwyems vnfd for gvnfm

topology_template:
  inputs:
    DC_ID:
      type: string
      description: DC_ID
    ak:
      type: string
      default: abdc
      description: AK
    sk:
      type: string
      default: 1234
      description: SK
    mep_certificate:
      type: text
      default: YHXGFTWU!@$%@&%#(DH(122479+_)
      description: MEP Certificate
    app_mp1_ip:
      type: string
      default:
      description: app_mp1_ip
    app_mp1_mask:
      type: string
      default:
      description: app_mp1_mask
    app_mp1_gw:
      type: string
      default:
      description: app_mp1_gw
    app_n6_ip:
      type: string
      default:
      description: app_n6_ip
    app_n6_mask:
      type: string
      default:
      description: app_n6_mask
    app_internet_ip:
      type: string
      default:
      description: app_internet_ip
    app_internet_mask:
      type: string
      default:
      description: app_internet_mask
    app_internet_gw:
      type: string
      default:
      description: app_internet_gw
    mep_ip:
      type: string
      default:
      description: mep_ip
    mep_port:
      type: string
      default:
      description: mep_port

    network_name_mep:
      type: string
      default: mec_network_mep
      description: network_name_mep
    network_mep_physnet:
      type: string
      default: network_mep_physnet
      description: network_mep_physnet
    network_mep_vlanid:
      type: string
      default: network_mep_vlanid
      description: network_mep_vlanid
    network_name_n6:
      type: string
      default: mec_newwork_n6
      description: network_name_n6
    network_n6_physnet:
      type: string
      default: network_n6_physnet
      description: network_n6_physnet
    network_n6_vlanid:
      type: string
      default: network_n6_vlanid
      description: network_n6_vlanid
    network_name_internet:
      type: string
      default: mec_newwork_internet
      description: network_name_internet
    network_internet_physnet:
      type: string
      default: network_internet_physnet
      description: network_internet_physnet
    network_internet_vlanid:
      type: string
      default: network_internet_vlanid
      description: network_internet_vlanid
    ue_ip_segment:
      type: string
      default: 0.0.0.0/0
      description: ue_ip_segment

    INTERNAL_IP_VERSION:
      type: string
      default: IPV4
      description: INTERNAL_IP_VERSION
    DEMO_VNF_Network_01:
      type: string
      default: app_arm
      description: DEMO_VNF_Network_01
    DEMO_VNF_Network_02:
      type: string
      default: app_arm
      description: DEMO_VNF_Network_02
  node_templates:
    Simple_VNF:
      type: tosca.nodes.nfv.VNF
      properties:
        vnfd_id: eulerforTR6_iso_arm_zhi_new1
        vnfd_version: v1.0
        provider: eastcom
        product_name: vSPCLNLWYEMS
        software_version: v1.0.0
        product_info_name: vSPCLNLWYEMS
        product_info_description: EASTCOM vSPCLNLWY EMS
        flavour_id: default
        flavour_description: default flavor
        ve_vnfm_vnf_enable: false
        ve_vnfm_em_enable: false

    EMS_VDU1:
      type: tosca.nodes.nfv.Vdu.Compute
      capabilities:
        virtual_compute:
          properties:
            virtual_memory:
              virtual_mem_size: 4096
            virtual_cpu:
              num_virtual_cpu: 4
              cpu_architecture: ARM
            virtual_local_storage:
              size_of_storage: 100
      properties:
        name: eulerforTR6_iso_arm_EMS_VDU1
        description: EMS_VDU1 node
        nfvi_constraints: 'nova'
        vdu_profile:
          min_number_of_instances: 1
          max_number_of_instances: 1
          initial_number_of_instances: 1
          flavor_extra_specs:
            "mgmt_egx86": "true"
        sw_image_data:
          name: ubuntu
        bootdata:
          config_drive: true
          user_data:
            contents: |
            params:
    EMS_VDU1_CP0:
      type: tosca.nodes.nfv.VduCp
      properties:
        description: to mep
        vnic_name: eth0
        order: 0
        vnic_type: normal
        port_security_enabled: true
      requirements:
        - virtual_binding: EMS_VDU1
        - virtual_link: MEC_APP_MP1

    EMS_VDU1_CP1:
      type: tosca.nodes.nfv.VduCp
      properties:
        description: internal
        vnic_name: eth1
        order: 1
        vnic_type: normal
        port_security_enabled: true
      requirements:
        - virtual_binding: EMS_VDU1
        - virtual_link: MEC_APP_INTERNET

    EMS_VDU1_CP2:
      type: tosca.nodes.nfv.VduCp
      properties:
        description: to UFP&OM
        vnic_name: eth2
        order: 2
        vnic_type: normal
        port_security_enabled: true
      requirements:
        - virtual_binding: EMS_VDU1
        - virtual_link: MEC_APP_N6

    MEC_APP_MP1:
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: network_name_mep}
          network_type: vlan
          physical_network: {get_input: network_mep_physnet}
          provider_segmentation_id: {get_input: network_mep_vlanid}

    MEC_APP_INTERNET:
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: network_name_internet}
          network_type: vlan
          physical_network: {get_input: network_internet_physnet}
          provider_segmentation_id: {get_input: network_internet_vlanid}

    MEC_APP_N6:
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: network_name_n6}
          network_type: vlan
          physical_network: {get_input: network_n6_physnet}
          provider_segmentation_id: {get_input: network_n6_vlanid}
    app_configuration:
      type: tosca.nodes.nfv.app.configuration
      properties:
        certification_info:
          access_key_id: {get_input: ak}
          secret_key: {get_input: sk}



    DEMO_VL1: # 使用虚拟层中已经创建的网络名称或UUID。
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: DEMO_VNF_Network_01}

    DEMO_VL2: # 使用虚拟层中已经创建的网络名称或UUID。
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        vl_profile:
          network_name: {get_input: DEMO_VNF_Network_02}

  groups:
    AntiAffinityGroup:
      type: tosca.groups.nfv.PlacementGroup
      properties:
        description: antiaffinity group
      members:
      - EMS_VDU1
  policies:
    - antiaffinity_policy:
        type: tosca.policies.nfv.AntiAffinityRule
        targets:
        - AntiAffinityGroup
        properties:
          scope: nfvi_node
          enforced: true
