global:
  mepagent:
    enabled: <IS_MEP_AGENT>
  namespace:
    enabled: <IS_NAMESPACE>

appconfig:
  appnamespace: <NAMESPACE>
  aksk:
    secretname: <random_value>
    accesskey: <akvalue>
    secretkey: <skvalue>
    appInsId: <idvalue>

serviceconfig:
#  - servicename: positioning-service
#    port: 9997
#    version: 1.0
#    protocol: HTTP
#    appnamespace: default
