tosca_definitions_version: tosca_simple_profile_yaml_1_1
description: the VNFD of Huawei SBC

node_types:
  org.openecomp.resource.app.template:
    derived_from: tosca.nodes.nfv.VNF
    properties:
      descriptor_id:
        type: string
        constraints: 
        - valid_values: 
          - b1bb0ce7-ebca-4fa7-95ed-4840d70a1177
        default: b1bb0ce7-ebca-4fa7-95ed-4840d70a1177
      provider:
        type: string
        constraints:
        - valid_values:
          - Huawei
        default: Huawei
      product_name:
        type: string
        constraints:
        - valid_values:
          - template
        default: template
      software_version:
        type: string
        constraints:
        - valid_values:
          - 1.0
        default: 1.0
      descriptor_version:
        type: string
        constraints:
        - valid_values:
          - 1.0
        default: 1.0   
topology_template: 
  node_templates:
    template:
      type: org.openecomp.resource.app.template
      properties:
      descriptor_id: b1bb0ce7-ebca-4fa7-95ed-4840d70a1177
      provider: Huawei
      product_name: template
      software_version: '1.0'
      descriptor_version: '1.0'
      requirements:
      - virtual_link:
          capability: tosca.capabilities.nfv.VirtualLinkable
          node: LBU_ACCESS
      - virtual_link:
          capability: tosca.capabilities.nfv.VirtualLinkable
          node: HRU_ACCESS
      
    logic:
      type: tosca.nodes.nfv.Vdu.Compute
      properties:
        name: logic
        description: logic
        image: template_app
        image_version: v1.4
        vdu_mec_host_requirements:
         mec_host_GPU_affinity:
             schemaVersion: 0
             schemaSelector: " "
             hardwarePlatform: "Huawei"
             mandatory: true
             configurationValue: "GPU"
         mec_host_mem_affinity:
             schemaVersion: 0
             schemaSelector: " "
             hardwarePlatform: "Huawei"
             mandatory: true
             configurationValue: "memory"
         mec_host_cpu_affinity:
             schemaVersion: 0
             schemaSelector: " "
             hardwarePlatform: "arm"
             mandatory: true
             configurationValue: "shared"
        vdu_profile:
          min_number_of_instances: 1
          max_number_of_instances: 4
      capabilities:
        virtual_compute:
          properties:
            virtual_memory:
              virtual_mem_size: 8096 MB
            virtual_cpu:
              cpu_architecture: x86
              num_virtual_cpu: 2
              virtual_cpu_clock: 1800 MHz
      requirements:
      - virtual_storage:
          capability: tosca.capabilities.nfv.VirtualStorage
          node: logic_Storage   

    logic1:
      type: tosca.nodes.nfv.Vdu.Compute
      properties:
        name: logic
        description: logic
        image: postgres
        image_version: 9.6.15
        vdu_mec_host_requirements:
         mec_host_GPU_affinity:
             schemaVersion: 0
             schemaSelector: " "
             hardwarePlatform: "Huawei"
             mandatory: true
             configurationValue: "GPU"
         mec_host_mem_affinity:
             schemaVersion: 0
             schemaSelector: " "
             hardwarePlatform: "Huawei"
             mandatory: true
             configurationValue: "memory"
         mec_host_cpu_affinity:
             schemaVersion: 0
             schemaSelector: " "
             hardwarePlatform: "arm"
             mandatory: true
             configurationValue: "shared"
        vdu_profile:
          min_number_of_instances: 1
          max_number_of_instances: 4
      capabilities:
        virtual_compute:
          properties:
            virtual_memory:
              virtual_mem_size: 8096 MB
            virtual_cpu:
              cpu_architecture: x86
              num_virtual_cpu: 2
              virtual_cpu_clock: 1800 MHz
      requirements:
      - virtual_storage:
          capability: tosca.capabilities.nfv.VirtualStorage
          node: logic_Storage 

    logic2:
      type: tosca.nodes.nfv.Vdu.Compute
      properties:
        name: logic
        description: logic
        image: redis
        image_version: alpine
        vdu_mec_host_requirements:
         mec_host_GPU_affinity:
             schemaVersion: 0
             schemaSelector: " "
             hardwarePlatform: "Huawei"
             mandatory: true
             configurationValue: "GPU"
         mec_host_mem_affinity:
             schemaVersion: 0
             schemaSelector: " "
             hardwarePlatform: "Huawei"
             mandatory: true
             configurationValue: "memory"
         mec_host_cpu_affinity:
             schemaVersion: 0
             schemaSelector: " "
             hardwarePlatform: "arm"
             mandatory: true
             configurationValue: "shared"
        vdu_profile:
          min_number_of_instances: 1
          max_number_of_instances: 4
      capabilities:
        virtual_compute:
          properties:
            virtual_memory:
              virtual_mem_size: 8096 MB
            virtual_cpu:
              cpu_architecture: x86
              num_virtual_cpu: 2
              virtual_cpu_clock: 1800 MHz
      requirements:
      - virtual_storage:
          capability: tosca.capabilities.nfv.VirtualStorage
          node: logic_Storage        
  
    logic_Storage:
      type: tosca.nodes.nfv.Vdu.VirtualStorage
      properties:
        type_of_storage: logic_Storage
        size_of_storage: 4G
        rdma_enabled:  true     

    logic_cp:
      type: tosca.nodes.nfv.VduCp
      properties:
        layer_protocol: [ ipv4 ]
        role: leaf
        description: External connection point to access LBU_access
      requirements:
      - virtual_link:
          capability: tosca.capabilities.nfv.VirtualLinkable
          node: logic_network
      - virtual_binding: 
          capability: tosca.capabilities.nfv.VirtualBindable
          node: logic   
    
    logic_network:
      type: tosca.nodes.nfv.VnfVirtualLink
      properties:
        connectivity_type:
          layer_protocol: [ ipv4 ]
          flow_pattern: mesh
        description:  network for logic app
        vl_profile:
          cidr: 192.168.1.24/24
          networkName: LBU_ACCESS
          startIp: 192.168.1.1
          endIp: 192.168.1.10
          gatewayIp: 192.168.1.0
          segmentationId: 4000
          physicalNetwork: physicalNetwork
          networkType: VLAN
          dhcpEnabled: true
          vlanTransparent: false
