swagger: "2.0"
info:
  description: "Cartoonizes an input image by using the CartoonGAN model."
  version: "2.1-alpine"
  title: "Apache APISIX"

basePath: "/ascend/v1/cartoon"
tags:
- name: "AI Cartoonize"
  description: "Cartoonizes an input image by using the CartoonGAN model."

schemes:
- "http"
paths:
  /input:
    post:
      tags:
      - "Cartoonize"
      summary: "Upload imag to be Cartoonized"
      description: "Upload imag to be Cartoonized"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "To be cartoonized image"
        required: true
        schema:
          $ref: "#/definitions/Request"
      responses:
        "400":
          description: "Bad Request"
        "200":
          description: "result id"  
          schema:
            $ref: "#/definitions/Response"
  /output/{id}:
    get:
      tags:
      - "Cartoonize"
      summary: "Get the output image"
      description: "Get the output image"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Output image ID"
        required: true
        type: "string"

      responses:
        "400":
          description: "Bad Request"
        "200":
          description: "Output image"  

definitions:
  Request:
    type: "object"
    properties: 
      image:
        type: "string"
        description: "image to be cartoonized"

  Response:
    type: "object"
    properties: 
      outputId:
        type: "string"
        description: "Output Id to get the file later"