swagger: '2.0'
info:
  version: '1.0'
  title: Resize an Image
  description: Resize an input image to the insput scale
  contact: {}
host: 127.0.0.1:8080
basePath: /ascend/v1/resizePic
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /input:
    post:
      description: Upload the Original image and scale to regenarte the image
      summary: ResizePicPOST
      tags:
      - ResizePic
      operationId: ResizePicPOST
      deprecated: false
      produces:
      - application/json
      consumes:
      - multipart/form-data
      parameters:
      - name: image
        in: formData
        required: true
        type: file
        format: file
        description: Image to be resized
      - name: scale
        in: formData
        required: true
        type: string
        description: The proportion in which image should resized
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Response'
          headers: {}
        400:
          description: Bad Request
          schema:
            type: object
          headers: {}
  /output/{outputId}:
    get:
      description: Get the output Image
      summary: ResizePicGET
      tags:
      - ResizePic
      operationId: ResizePicGET
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: outputId
        in: path
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            type: string
            format: binary
          headers: {}
        404:
          description: resource not found
          schema:
            type: object
          headers: {}
definitions:
  Response:
    title: Response
    type: object
    properties:
      outputId:
        description: Output Id to get the output file later
        type: string
    required:
    - outputId
tags:
- name: ResizePic
  description: ''
