tosca_definitions_version: tosca_simple_profile_yaml_1_2
description: the VNFD definition

metadata:
  template_name: EdgeGallery-Template-positioning-service
  template_author: EdgeGallery
  template_version: 1.0.0
  vnfm_type: MEPM
  vnfd_id: EdgeGallery-positioning-service
  vnfd_version: v1.0
  vnfd_name: EdgeGallery_MEC_Sample_APPD
  vnfd_description: EdgeGallery MEC sample for vnf

topology_template:
  node_templates:
    Simple_VNF:
      type: tosca.nodes.nfv.VNF
      properties:
        vnfd_id: EdgeGallery-positioning-service
        vnfd_version: v1.0
        provider: EdgeGallery
        product_name: MEC
        software_version: v1.0.0
        product_info_name: vMEC_APP
        product_info_description: EdgeGallery MEC APP
        flavour_id: default
        flavour_description: default flavor
        ve_vnfm_vnf_enable: false
        ve_vnfm_em_enable: false

    logic0:
      type: tosca.nodes.nfv.Vdu.Compute
      properties:
        name: logic0
        description: node logic template
        sw_image_data:
          name: "mep-agent:v1.0.1, position_service:1.0"
        vdu_mec_host_requirements:
          mec_host_mem_affinity:
            schemaVersion: 0
            schemaSelector: " "
            hardwarePlatform: "EdgeGallery"
            mandatory: true
            configurationValue: "memory"
          mec_host_cpu_affinity:
            schemaVersion: 0
            schemaSelector: " "
            hardwarePlatform: "EdgeGallery"
            mandatory: true
            configurationValue: "shared"
        vdu_profile:
          min_number_of_instances: 1
          max_number_of_instances: 2
          initial_number_of_instances: 1
          flavor_extra_specs:
            "X86_HA": 'true'
      capabilities:
        virtual_compute:
          properties:
            virtual_memory:
              virtual_mem_size: 4096
            virtual_cpu:
              num_virtual_cpu: 4
              cpu_architecture: X86
            virtual_local_storage:
              size_of_storage: 20

  groups:
    AntiAffinityGroup:
      type: tosca.groups.nfv.PlacementGroup
      properties:
        description: antiaffinity group
        members: [logic0]
#      members: [logic0, logic1]

  policies:
    - antiaffinity_policy:
        type: tosca.policies.nfv.AntiAffinityRule
        targets: [AntiAffinityGroup]
        properties:
          scope: nfvi_node
          enforced: true