---
apiVersion: v1
kind: Pod
metadata:
  name: {name}-deployment-{timeStamp}
  labels:
    app: {name}
spec:
  containers:
    - name: mep-agent
      image: edgegallery/mep-agent:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8057
      volumeMounts:
        - name: mep-agent-config-volume
          mountPath: /usr/app/conf
---IMAGE_LOOP_START---
    - name: {imageNameSpe}
      image: {imageName}:{imageVersion}
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: {imageContainerPort}
          protocol: TCP
    - name: mesher-sidecar-{imageNameSpe}
      image: edgegallery/mesher-sidecar:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: SPECIFIC_ADDR
          value: 127.0.0.1:{imageContainerPort}
      ports:
        - containerPort: {imageNodePort}
      volumeMounts:
        - name: mesher-config-volume-{imageNameSpe}
          mountPath: tmp
---IMAGE_LOOP_END---
  volumes:
    - name: mep-agent-config-volume
      configMap:
        name: mep-agent-config
---IMAGE_LOOP_START---
    - name: mesher-config-volume-{imageNameSpe}
      configMap:
        name: mesher-config-{imageNameSpe}
---IMAGE_LOOP_END---